"use strict";

const FORM_DEFS = {
  "abilities.json": {
    label: "Abilities",
    type: "array",
    displayName: (e) => `${e.id ?? "?"}: ${e.name || "unnamed"}`,
    fields: [
      { key: "id", label: "ID", type: "int" },
      { key: "name", label: "Name", type: "string" },
      { key: "animFile", label: "Anim File", type: "string" },
      { key: "animTag", label: "Anim Tag", type: "string" },
      { key: "playerAnim", label: "Player Anim", type: "string" },
      { key: "sfx", label: "SFX", type: "string" },
      { key: "baseDamage", label: "Base Damage", type: "int", min: -9999 },
      { key: "apCost", label: "AP Cost", type: "int", min: 0 },
      { key: "friendly", label: "Friendly", type: "bool" },
      { key: "description", label: "Description", type: "string" },
    ],
    defaultEntry: (data) => ({
      id: Math.max(-1, ...data.map((e) => e.id || 0)) + 1,
      name: "New Ability", animFile: "", animTag: "", playerAnim: "",
      sfx: "", baseDamage: 1, apCost: 1, friendly: false, description: "",
    }),
  },

  "battleDB.json": {
    label: "Battle DB",
    type: "array",
    displayName: (e) => `${e.id ?? "?"}: ${e.name || "unnamed"}`,
    fields: [
      { key: "id", label: "ID", type: "int" },
      { key: "name", label: "Name", type: "string" },
      { key: "nick", label: "Nick", type: "string" },
      { section: "Stats" },
      { key: "hp", label: "HP", type: "int", min: 1 },
      { key: "str", label: "STR", type: "int" },
      { key: "mag", label: "MAG", type: "int" },
      { key: "def", label: "DEF", type: "int" },
      { key: "mdef", label: "MDEF", type: "int" },
      { key: "spd", label: "SPD", type: "int" },
      { key: "pow", label: "POW", type: "int" },
      { key: "maxAP", label: "Max AP", type: "int", min: 1 },
      { section: "XP" },
      { key: "xpReward", label: "XP Reward", type: "int" },
      { key: "currentXP", label: "Current XP", type: "int" },
      { key: "xpToNextLevel", label: "XP To Next Level", type: "int" },
      { section: "Visuals" },
      { key: "sprite", label: "Sprite", type: "string" },
      { key: "portrait", label: "Portrait", type: "string" },
      { key: "portraitRect", label: "Portrait Rect", type: "rect" },
      { key: "rect", label: "Draw Rect", type: "rect" },
      { key: "idle", label: "Idle Anim", type: "string" },
      { section: "Offsets" },
      { key: "damageOffsetY", label: "Damage Offset Y", type: "int" },
      { key: "hpBarOffsetX", label: "HP Bar Offset X", type: "int" },
      { key: "hpBarOffsetY", label: "HP Bar Offset Y", type: "int" },
      { key: "animOffsetX", label: "Anim Offset X", type: "int" },
      { key: "animOffsetY", label: "Anim Offset Y", type: "int" },
      { section: "Battle" },
      { key: "ai", label: "AI Type", type: "string" },
      { key: "abilities", label: "Abilities (IDs)", type: "intlist" },
      { key: "itemDrops", label: "Item Drops", type: "sublist", subfields: [
        { key: "name", label: "Name", type: "string" },
        { key: "percent", label: "%", type: "int" },
      ]},
    ],
    defaultEntry: (data) => ({
      id: Math.max(-1, ...data.map((e) => e.id || 0)) + 1,
      name: "New Battler", nick: "",
      hp: 10, str: 5, mag: 5, def: 5, mdef: 3, spd: 3, pow: 100,
      maxAP: 3, xpReward: 0, currentXP: 0, xpToNextLevel: 100,
      sprite: "", portrait: "",
      portraitRect: { x: 0, y: 0, w: 48, h: 48 },
      rect: { x: 0, y: 0, w: 48, h: 48 },
      idle: "idle1",
      damageOffsetY: 0, hpBarOffsetX: 0, hpBarOffsetY: 0,
      animOffsetX: 0, animOffsetY: 0, ai: "basic",
      abilities: [0], itemDrops: [],
    }),
  },

  "battleZones.json": {
    label: "Battle Zones",
    type: "array",
    displayName: (e) => `Zone ${e.id ?? "?"}`,
    fields: [
      { key: "id", label: "ID", type: "int" },
      { key: "encounterTime", label: "Encounter Time (s)", type: "float" },
      { key: "groups", label: "Group IDs", type: "intlist" },
      { key: "maps", label: "Map Names", type: "strlist" },
    ],
    defaultEntry: (data) => ({
      id: Math.max(-1, ...data.map((e) => e.id || 0)) + 1,
      encounterTime: 2.0, groups: [], maps: [],
    }),
  },

  "playerCharacters.json": {
    label: "Players",
    type: "array",
    displayName: (e) => `${e.id ?? "?"}: ${e.name || "unnamed"}`,
    fields: [
      { key: "id", label: "ID", type: "int" },
      { key: "name", label: "Name", type: "string" },
      { key: "description", label: "Description", type: "string" },
      { key: "nick", label: "Nick", type: "string" },
      { section: "Sprites" },
      { key: "overworldSprite", label: "Overworld Sprite", type: "string" },
      { key: "battleSprite", label: "Battle Sprite", type: "string" },
      { key: "portrait", label: "Portrait", type: "string" },
      { key: "portraitRect", label: "Portrait Rect", type: "rect" },
      { key: "idle", label: "Idle Anim", type: "string" },
      { section: "Config" },
      { key: "battlerDBIndex", label: "BattlerDB Index", type: "int" },
      { key: "overworldFrameW", label: "Frame Width", type: "int" },
      { key: "overworldFrameH", label: "Frame Height", type: "int" },
    ],
    defaultEntry: (data) => ({
      id: Math.max(-1, ...data.map((e) => e.id || 0)) + 1,
      name: "New Character", description: "", nick: "NEW",
      overworldSprite: "", battleSprite: "", portrait: "",
      portraitRect: { x: 0, y: 0, w: 48, h: 48 },
      idle: "idle1", battlerDBIndex: 0,
      overworldFrameW: 26, overworldFrameH: 36,
    }),
  },

  "battleGroups.json": {
    label: "Battle Groups",
    type: "groups",
  },

  "gameConfig.json": {
    label: "Game Config",
    type: "config",
    layout: [
      { section: "Logos" },
      { key: "logos", label: "Logo Textures", type: "strlist", path: ["logos"] },
      { section: "Audio" },
      { key: "bgmVolume", label: "BGM Volume (0-1)", type: "float", path: ["audio", "bgmVolume"] },
      { key: "sfxVolume", label: "SFX Volume (0-1)", type: "float", path: ["audio", "sfxVolume"] },
      { section: "Window" },
      { key: "winX", label: "Render Width", type: "int", path: ["window", "x"] },
      { key: "winY", label: "Render Height", type: "int", path: ["window", "y"] },
      { key: "xWin", label: "Window Width", type: "int", path: ["window", "xWin"] },
      { key: "yWin", label: "Window Height", type: "int", path: ["window", "yWin"] },
      { key: "title", label: "Window Title", type: "string", path: ["window", "title"] },
      { section: "Scenes" },
      { key: "defaultScene", label: "Default Scene", type: "string", path: ["scene", "defaultScene"] },
      { key: "scenes", label: "Scene List", type: "sublist", path: ["scene", "scenes"], subfields: [
        { key: "MapName", label: "Map", type: "string" },
        { key: "UIName", label: "UI", type: "string" },
        { key: "BGMName", label: "BGM", type: "string" },
        { key: "BGMVolume", label: "Vol", type: "float" },
        { key: "DisplayName", label: "Display", type: "string" },
      ]},
    ],
  },
};

function isDialogFile(name) {
  return name.endsWith("D.json") && !FORM_DEFS[name];
}
